name: Update Sitemap

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate sitemap.xml with updated lastmod
      run: |
        TODAY=$(date +%F)
        cat > sitemap.xml <<EOL
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
            <loc>https://prudhwiraj1.github.io/</loc>
            <lastmod>$TODAY</lastmod>
            <changefreq>monthly</changefreq>
            <priority>1.0</priority>
          </url>
        </urlset>
        EOL

    - name: Commit and Push sitemap.xml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Update sitemap.xml with current date" || echo "No changes"
        git push
